config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  get 'signup', to: 'users#new'
  get 'login', to: 'session#new'
  post 'login', to: 'session#create'
  delete 'logout', to: 'session#destroy'
  
  resources :users do
    member do
      get 'followings'
      get 'followers'
      get 'like'
    end
  end
  
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts
  resources :relationships, only: [:create, :destroy]
  resources :likes, only: [:create, :destroy]
  
end

app/models/like.rb
class Like < ActiveRecord::Base
    belongs_to :user
    belongs_to :micropost

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  belongs_to :user
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
  paginates_per 10
  
  has_many :likes
  has_many :liking_users, through: :likes, source: :user
  
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  paginates_per 3
  
  has_secure_password
  has_many :microposts
  
  has_many :following_relationships, class_name: "Relationship",
                                     foreign_key: "follower_id",
                                     dependent:   :destroy
  has_many :following_users, through: :following_relationships, source: :followed

  has_many :follower_relationships, class_name: "Relationship",
                                    foreign_key: "followed_id",
                                    dependent:  :destroy
  
  has_many :follower_users, through: :follower_relationships, source: :follower
  
  has_many :likes
  has_many :like_microposts, through: :likes, source: :micropost
  
  
  # 他のユーザーをフォローする
  def follow(other_user)
    following_relationships.find_or_create_by(followed_id: other_user.id)
  end
  
  # フォローしているユーザーをアンフォローする
  def unfollow(other_user)
    following_relationship = following_relationships.find_by(followed_id: other_user.id)
    following_relationship.destroy if following_relationship
  end
  
  # あるユーザーをフォローしているかどうか？
  def following?(other_user)
    following_users.include?(other_user)
  end
  
  def feed_items
    Micropost.where(user_id: following_user_ids + [self.id])
  end
  
  def like?(micropost)
    like_microposts.include?(micropost)
  end
  
  def like!(micropost)
    likes.find_or_create_by(micropost_id: micropost.id)
  end
  
  def unlike!(micropost)
    likes.find_by(micropost_id: micropost.id).destroy
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
  
  private
  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "ログインしてください"
      redirect_to login_url
    end
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = current_user.likes.build(micropost_id: params[:micropost_id])
    @like.save
    redirect_to :back
  end
  
  def destroy
    @like = current_user.likes.find_by(micropost_id: params[:id]) 
    @like.destroy
    redirect_to :back
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
    before_action :logged_in_user, only: [:create, :destroy]

    def create
        @micropost = current_user.microposts.build(micropost_params)
        if @micropost.save
            flash[:success] = "Micropost created!"
            redirect_to root_url
        else
            @feed_items = current_user.feed_items.includes(:user).order(created_at: :desc)
            render 'static_pages/home'
        end
    end
    
    def destroy
        @micropost = current_user.microposts.find_by(id: params[:id])
        return redirect_to root_url if @micropost.nil?
        @micropost.destroy
        flash[:success] = "Micropost deleted"
        redirect_to request.referrer || root_url
    end
    
    private
    def micropost_params
        params.require(:micropost).permit(:content)
    end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
    before_action :logged_in_user
    
    def create
        @user = User.find(params[:followed_id])
        current_user.follow(@user)
    end
    
    def destroy
        @user = current_user.following_relationships.find(params[:id]).followed
        current_user.unfollow(@user)
    end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end
  
  def create
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      flash[:info] = "ログインに成功しました"
      redirect_to @user
    else
      flash[:danger] = "メールアドレスもしくはパスワードが正しくありません"
      render 'new'
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @micropost = current_user.microposts.build
      @feed_items = current_user.feed_items.includes(:user).order(created_at: :desc).page(params[:page])
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_users, only: [:show, :edit, :update, :followings, :followers, :like]
  before_action :authenticate, only: [:edit, :update,]
  before_action :logged_in_user, only: [:followings, :followers, :like]

  def show
    #@users = User.page(params[:page])
    @microposts = @user.microposts.order(created_at: :desc).page(params[:page])
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "登録が完了しました。"
      session[:user_id] = @user.id
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def edit
  end
  
  def update
    if @user.update(user_params)
      # 変更に成功した場合は、idページへリダイレクト
      redirect_to user_path, notice: "プロフィールを変更しました。"
    else
      # 変更に失敗した場合は編集画面へ戻す
      render 'edit'
    end
  end
  
  def followings
    @user = User.find(params[:id])
    @users = @user.following_users.page(params[:page])
  end
  
  def followers
    @user = User.find(params[:id])
    @users = @user.follower_users.page(params[:page])
  end
  
  def like
    @title = 'いいね一覧'
    @micropost = current_user.microposts.build
    @feed_microposts = current_user.like_microposts
  end
  
  private
  
  def set_users
    @user = User.find(params[:id])
  end

  def authenticate
    redirect_to root_url unless @user == current_user
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :introduction, :birthday)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end
    
    def logged_in?
        !!current_user
    end
    
    def store_location
        session[:forwarding_url] = request.url if request.get?
    end
end

app/helpers/users_helper.rb
module UsersHelper
    def gravatar_for(user, options = { size: 80 })
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        size = options[:size]
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.name, class: "gravatar")
    end
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Microposts", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "ホーム", root_path %></li>
        <li><%= link_to "ヘルプ", '#' %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", '#' %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              アカウント <b class="caret"></b>
            </a>
          <ul class="dropdown-menu">
            <li><%= link_to "プロフィール", current_user %></li>
            <li><%= link_to "設定", '#' %></li>
            <li class="divider"></li>
            <li>
              <%= link_to "ログアウト", logout_path, method: "delete" %>
            </li>
          </ul>
        </li>
        <% else %>
          <li><%= link_to "ログイン", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Microposts</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
<%= yield %>
</div>
</body>
</html>

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
    <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
    <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
    <span class="content"><%= micropost.content %></span>
    <span class="timestamp">
        Posted <%= time_ago_in_words(micropost.created_at) %> ago.
    <% if current_user == micropost.user %>
        <%= link_to "delete", micropost, method: :delete, data: { confirm: "本当に削除しますか？" } %>
    <% end %>
    <% if logged_in? %>
        <% if current_user.like?(micropost) %>
            <%= link_to "いいね！を取り消す", like_path(micropost),method: :delete %>
        <% else %>
            <%= link_to "いいね！", likes_path(micropost_id: micropost.id),method: :post %>
        <% end %>
    <% end %>
    </span>
</li>

app/views/relationships/create.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/unfollow')) %>");

app/views/relationships/destroy.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/follow')) %>");

app/views/session/new.html.erb
<h1>ログイン</h1>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= form_for(:session, url: login_path) do |f| %>

            <%= f.label :email %>
            <%= f.email_field :email, class: 'form-control' %>
        
            <%= f.label :password %>
            <%= f.password_field :password, class: 'form-control' %>
            
            <%= f.submit "ログイン", class: "btn btn-primary" %>
        <% end %>
    
        <p><%= link_to "新規登録の方はこちら", signup_path %></p>
    </div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
    <ol class="microposts">
        <%= render @feed_items %>
    </ol>
    <%= paginate @feed_items %>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="field">
        <%= f.text_area :content, placeholder: "Compose new micropost..." %>
    </div>
    <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "プロフィール", current_user %></span>
<span><%= pluralize(current_user.microposts.count, "micropost") %></span>

app/views/static_pages/home.html.erb
<% if logged_in? %>
    <div class="row">
        <aside class="col-md-4">
            <section class="user_info">
                <%= render 'shared/user_info' %>
            </section>
            <section class="micropost_form">
                <%= render 'shared/micropost_form' %>
            </section>
        </aside>
        <div class="col-md-8">
            <h3>タイムライン</h3>
            <%= render 'shared/feed' %>
        </div>
    </div>
<% else %>
    <div class="center jumbotron">
        <h1>Welcome to the Microposts</h1>
        
        <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
    </div>
<% end %>

app/views/users/_follow.html.erb
<%= form_for(current_user.following_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% if current_user != @user %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_profile.html.erb
<aside class="col-md-4">
        <section class="user_info">
            <h1>
                <%= gravatar_for @user %>
                <%= @user.name %>
            </h1>
            <%= link_to "フォロー", followings_user_path(@user) %>
            <%= link_to "フォロワー", followers_user_path(@user) %>
            <%= link_to "いいね", like_user_path(@user) %>
            <div class="profile-table">
                <table class="table">
                    <tbody>
                        <% if @user.introduction.present? %>
                            <tr>
                                <th>自己紹介</th>
                                <td><%= @user.introduction %></td>
                            </tr>
                        <% end %>
                        <% if @user.birthday.present? %>
                            <tr>
                                <th>誕生日</th>
                                <td><%= @user.birthday %></td>
                            </tr>
                        <% end %>
                            <tr>
                                <th>メールアドレス</th>
                                <td><%= @user.email %></td>
                            </tr>
                    </tbody>
                </table>
            </div>
            <% if @user == current_user %>
                <%= link_to "プロフィールの編集", edit_user_path, { :class => "btn btn-primary" } %>
            <% end %>
        </section>
    </aside>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.following_relationships.find_by(followed_id: @user.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/edit.html.erb
<div class="row">
    <h1>プロフィールの編集</h1>
    <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        <div class="form-horizontal">
            <div class="form-group">
                <div class="col-xs-2">
                    名前<%= f.text_field :name, class: "form-control" %>
                </div>
            </div>
            <div class="form-group">
                <div class="col-xs-6">
                    自己紹介<%= f.text_area :introduction, class: "form-control", rows: "6" %>
                </div>
            </div>
            <div class="form-group">
                <div class="col-xs-2">
                    誕生日<%= f.date_field :birthday, class: "form-control" %>
                </div>
            </div>
            <div class="form-group">
                <div class="col-xs-3">
                    メールアドレス<%= f.email_field :email, class: "form-control" %>
                </div>
            </div>
            <div class="form-group">
                <div class="col-xs-3">
                    パスワード<%= f.password_field :password, class: "form-control" %>
                </div>
            </div>
            <div class="form-group">
                <div class="col-xs-3">
                    パスワード(確認)<%= f.password_field :password_confirmation, class: "form-control" %>
                </div>
            </div>
            <div class="form-group">
                <div class="col-xs-2">
                    <%= f.submit "変更を保存", class: "btn btn-primary" %>
                </div>
            </div>
        </div>
    <% end %>
</div>

app/views/users/followers.html.erb
<div class="row">
    <%= render 'users/profile' %>
    <div class="col-md-8">
        <% if @users.any? %>
            <h3>フォロワー(<%= @users.count %>)</h3>
                <ol class="followings">
                    <% @users.each do |user| %>
                        <li>
                            <%= link_to gravatar_for(user, size: 50), user %>
                            <span class="user"><%= link_to user.name, user %></span>
                        </li>
                    <% end %>
                </ol>
        <% end %>
    </div>
</div>

app/views/users/followings.html.erb
<div class="row">
    <%= render 'users/profile' %>
    <div class="col-md-8">
        <% if @users.any? %>
            <h3>フォロー(<%= @users.count %>)</h3>
                <ol class="followings">
                    <% @users.each do |user| %>
                        <li>
                            <%= link_to gravatar_for(user, size: 50), user %>
                            <span class="user"><%= link_to user.name, user %></span>
                        </li>
                    <% end %>
                </ol>
        <% end %>
        <%= paginate @users %>
    </div>
</div>

app/views/users/like.html.erb
<div class="row">
    <%= render 'users/profile' %>
    <div class="col-md-8">
        <h3><%= @title %></h3>
            <ol class="microposts">
                <%= render @feed_microposts %>
            </ol>
    </div>
</div>

app/views/users/new.html.erb
<h1>新規登録</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>

      <%= f.label :email %>
      <%= f.text_field :email, class: "form-control"  %>

      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control"  %>

      <%= f.label :password_confirmation, "パスワード(確認)" %>
      <%= f.password_field :password_confirmation, class: "form-control"  %>


      <%= f.submit "登録", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
    <%= render 'users/profile' %>
    <div class="col-md-8">
        <%= render 'follow_form' if logged_in? %>
        <% if @user.microposts.any? %>
            <h3>Microposts (<%= @user.microposts.count %>)</h3>
            <ol class="microposts">
                <%= render @microposts %>
            </ol>
            <%= paginate @microposts %>
        <% end %>
    </div>
</div>